import {useMemo,useRef,useState} from 'react';import DrawingCanvas from './components/DrawingCanvas';import GraphWorkspace from './components/GraphWorkspace';import TeacherLens from './components/TeacherLens';import TeacherBuilder from './components/TeacherBuilder';import {problems} from './data/problems';import type {Evidence,Problem} from './types/problem';import type {DrawingCanvasHandle} from './components/DrawingCanvas';import InkReader from './components/InkReader';import {analyzeWork,type Analysis} from './engine/analyzeWork';
const questions=['Show me what you notice first.','Tell me what you were trying to do there.','Let’s focus on one part. What has to stay true?','Want a smaller example or a visual model?','Let’s learn that piece together, then come back.'];
export default function App(){const [grade,setGrade]=useState(8),[index,setIndex]=useState(0),[attempts,setAttempts]=useState(0),[support,setSupport]=useState(0),[answer,setAnswer]=useState(''),[evidence,setEvidence]=useState<Evidence[]>([]),[teacher,setTeacher]=useState(false),[builder,setBuilder]=useState(false),[assigned,setAssigned]=useState<Problem[]>([]),[analysis,setAnalysis]=useState<Analysis|null>(null),[inkTick,setInkTick]=useState(0);const canvasRef=useRef<DrawingCanvasHandle>(null);const available=useMemo(()=>{const base=problems.filter(p=>grade>=p.minGrade&&grade<=p.maxGrade);const mine=assigned.filter(p=>grade>=p.minGrade&&grade<=p.maxGrade);return [...mine,...base]},[grade,assigned]);const p=available[index%available.length]||problems[0];
 const log=(detail:string,kind='work')=>setEvidence(v=>[...v,{time:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),kind,detail}]);
 const submit=()=>{if(!answer.trim())return;const n=attempts+1;setAttempts(n);log(`Student shared: ${answer}`);if(/3x\s*\+\s*4/.test(answer.replace(/\s/g,''))){setSupport(Math.max(support,2));log('Pattern detected: possible partial distribution','diagnosis')}setAnswer('')};
 const stuck=()=>{const s=Math.min(4,support+1);setSupport(s);const prompt=analysis?.next||questions[s];log(`Student requested contextual help → ${prompt}`,'support')};
 const analyzeLine=(line:string)=>{const a=analyzeWork(p.id,line);setAnalysis(a);setAttempts(v=>v+1);log(`Reader captured: ${line}`,'work');if(a.diagnosis)log(`Detected: ${a.diagnosis}`,'diagnosis');if(a.status==='misconception')setSupport(v=>Math.max(v,2));};
 const assign=(ps:Problem[])=>{setAssigned(ps);setIndex(0);setBuilder(false);setGrade(ps[0]?.minGrade||grade);setEvidence([]);setAttempts(0);setSupport(0);setAnalysis(null)};
 return <main><header><div><span className="brand">Math Tutor</span><span className="tag">6–12</span></div><div className="topControls"><label>Grade <select value={grade} onChange={e=>{setGrade(+e.target.value);setIndex(0)}}>{[6,7,8,9,10,11,12].map(g=><option key={g}>{g}</option>)}</select></label><button className="teacherCreate" onClick={()=>setBuilder(true)}>＋ Create assignment</button><button className="quiet" onClick={()=>setTeacher(!teacher)}>{teacher?'Hide':'Show'} Teacher Lens</button></div></header>
 <section className="shell"><div className="student">{assigned.length>0&&<div className="assignmentBanner"><b>Teacher assignment</b><span>{assigned.length} problem{assigned.length===1?'':'s'} ready</span></div>}<nav>{available.map((q,i)=><button key={q.id} className={i===index?'tab active':'tab'} onClick={()=>setIndex(i)}>{q.source==='teacher'?'★ ':''}{q.title}</button>)}</nav><div className="problem"><span className="skill">{p.skill}</span><h1>{p.prompt}</h1><p className="coach">💬 {questions[support]}</p></div>
 <section className="workspace"><h2>Show me your thinking</h2>{p.workspace==='graph'?<GraphWorkspace domain={/domain/i.test(p.skill+p.prompt)} onEvidence={log}/>:<><DrawingCanvas ref={canvasRef} onInk={()=>setInkTick(v=>v+1)}/><InkReader hasInk={!!canvasRef.current?.hasInk()||inkTick>0} onAnalyze={analyzeLine} analysis={analysis}/></>}<div className="response"><input aria-label="Share what you notice" placeholder={p.workspace==='graph'?'Tell me what you notice…':'Write or describe a step (optional)…'} value={answer} onChange={e=>setAnswer(e.target.value)} onKeyDown={e=>e.key==='Enter'&&submit()}/><button onClick={submit}>Share thinking</button><button className="stuck" onClick={stuck}>I’m stuck</button></div><p className="muted center">Try something, draw something, or tell the tutor what you notice. You do not need to know the “right next step.”</p></section></div>{teacher&&<TeacherLens attempts={attempts} support={support} evidence={evidence}/>}</section>{builder&&<TeacherBuilder grade={grade} onAssign={assign} onClose={()=>setBuilder(false)}/>}</main>}
